<?xml version="1.0" encoding="utf-8"?>
<!--Generated by Marushka, version 4.2.15.5, GEOVAP, spol. s r.o., 05.08.2025.-->
<FeatureCollection xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:base="http://inspire.ec.europa.eu/schemas/base/3.3" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:cp-ext="http://services.cuzk.cz/xsd/inspire/cp-ext/4.0" xmlns:gmd="http://www.isotc211.org/2005/gmd" xmlns:gco="http://www.isotc211.org/2005/gco" xmlns:cp="http://inspire.ec.europa.eu/schemas/cp/4.0" xmlns:gn="http://inspire.ec.europa.eu/schemas/gn/4.0" xmlns:gml="http://www.opengis.net/gml/3.2" xsi:schemaLocation="http://www.opengis.net/wfs/2.0 http://schemas.opengis.net/wfs/2.0/wfs.xsd http://www.opengis.net/gml/3.2 http://schemas.opengis.net/gml/3.2.1/gml.xsd http://inspire.ec.europa.eu/schemas/base/3.3 https://inspire.ec.europa.eu/schemas/base/3.3/BaseTypes.xsd  http://inspire.ec.europa.eu/schemas/cp/4.0 https://inspire.ec.europa.eu/schemas/cp/4.0/CadastralParcels.xsd http://services.cuzk.cz/xsd/inspire/cp-ext/4.0 https://services.cuzk.cz/xsd/inspire/cp-ext/4.0/CadastralParcelsExtended.xsd" timeStamp="2025-08-05T16:18:50" numberMatched="1" numberReturned="1" xmlns="http://www.opengis.net/wfs/2.0">
  <boundedBy>
    <gml:Envelope srsName="http://www.opengis.net/def/crs/EPSG/0/5514" srsDimension="2">
      <gml:lowerCorner>-732523.97 -1030013.91</gml:lowerCorner>
      <gml:upperCorner>-732491.12 -1029984.28</gml:upperCorner>
    </gml:Envelope>
  </boundedBy>
  <member>
    <cp:CadastralParcel gml:id="CP.3751356209">
      <cp:areaValue uom="m2">437</cp:areaValue>
      <cp:beginLifespanVersion>2019-03-04T15:16:24Z</cp:beginLifespanVersion>
      <cp:endLifespanVersion xsi:nil="true" nilReason="http://inspire.ec.europa.eu/codelist/VoidReasonValue/Unpopulated" />
      <cp:geometry>
        <gml:Polygon gml:id="P.CP.3751356209" srsName="http://www.opengis.net/def/crs/EPSG/0/5514" srsDimension="2">
          <gml:exterior>
            <gml:LinearRing>
              <gml:posList>-732504.15 -1030013.91 -732491.12 -1029991.35 -732521.65 -1029984.28 -732523.91 -1029994.03 -732523.97 -1029995.98 -732523.28 -1029997.8 -732521.95 -1029999.23 -732520.17 -1030000.03 -732519.19 -1030000.25 -732520.21 -1030004.64 -732504.15 -1030013.91</gml:posList>
            </gml:LinearRing>
          </gml:exterior>
          <gml:interior>
            <gml:LinearRing>
              <gml:posList>-732505.27 -1030007.8 -732515.3 -1030005.51 -732513.7 -1029998.32 -732512.4 -1029998.57 -732511.01 -1029992.12 -732502.16 -1029994.15 -732505.27 -1030007.8</gml:posList>
            </gml:LinearRing>
          </gml:interior>
        </gml:Polygon>
      </cp:geometry>
      <cp:inspireId>
        <base:Identifier>
          <base:localId>CP.3751356209</base:localId>
          <base:namespace>CZ-00025712-CUZK_CP</base:namespace>
        </base:Identifier>
      </cp:inspireId>
      <cp:label>95/43</cp:label>
      <cp:nationalCadastralReference>705411-95/43</cp:nationalCadastralReference>
      <cp:referencePoint>
        <gml:Point gml:id="R.CP.3751356209" srsName="http://www.opengis.net/def/crs/EPSG/0/5514" srsDimension="2">
          <gml:pos>-732516.87 -1029995.13</gml:pos>
        </gml:Point>
      </cp:referencePoint>
      <cp:validFrom xsi:nil="true" nilReason="http://inspire.ec.europa.eu/codelist/VoidReasonValue/Unpopulated" />
      <cp:administrativeUnit xlink:type="simple" xlink:href="http://services.cuzk.cz/wfs/inspire-au-wfs.asp?service=WFS&amp;VERSION=2.0.0&amp;request=GetFeature&amp;storedQuery_id=urn:ogc:def:query:OGC-WFS::GetFeatureById&amp;Id=AU.538558" xlink:title="Nová Ves u Prahy" />
      <cp:zoning xlink:type="simple" xlink:href="http://services.cuzk.cz/wfs/inspire-cp-wfs.asp?service=WFS&amp;VERSION=2.0.0&amp;request=GetFeature&amp;storedQuery_id=urn:ogc:def:query:OGC-WFS::GetFeatureById&amp;Id=CZ.705411" xlink:title="Nová Ves" />
    </cp:CadastralParcel>
  </member>
</FeatureCollection>